on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: akslab1911.azurecr.io
        username: ${{ secrets.acr_akslab1911_username }}
        password: ${{ secrets.acr_akslab1911_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t akslab1911.azurecr.io/myakscluster:${{ github.sha }}
        docker push akslab1911.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksclusterb4cb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksclusterb4cb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksclusterb4cb
        container-registry-url: akslab1911.azurecr.io
        container-registry-username: ${{ secrets.acr_akslab1911_username }}
        container-registry-password: ${{ secrets.acr_akslab1911_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksclusterb4cb
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          akslab1911.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth