on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myazurecontainerregistry1911.azurecr.io
        username: ${{ secrets.acr_myazurecontainerregistry1911_username }}
        password: ${{ secrets.acr_myazurecontainerregistry1911_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myazurecontainerregistry1911.azurecr.io/myakscluster:${{ github.sha }}
        docker push myazurecontainerregistry1911.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myakscluster9bbf | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myakscluster9bbf`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myakscluster9bbf
        container-registry-url: myazurecontainerregistry1911.azurecr.io
        container-registry-username: ${{ secrets.acr_myazurecontainerregistry1911_username }}
        container-registry-password: ${{ secrets.acr_myazurecontainerregistry1911_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myakscluster9bbf
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          myazurecontainerregistry1911.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth